
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:9000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_DATABASE: blog
      DB_USERNAME: fabietto
      DB_PASSWORD: 123
    depends_on:
      - db
    volumes:
      - ./:/var/www

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: fabietto
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
